### What is numpy?

NumPy is the fundamental package for scientific computing in Python. 

It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

### Data Structures: Scalar, Vector, Matrix, and Tensor

In NumPy, all data structures are instances of the ndarray class, categorized by their rank (number of dimensions):

- **Scalar (0D)**: A single numerical value with no dimensions (Rank 0).
   - Example: A single temperature reading like 25.
    - Shape: ()

- **Vector (1D)**: A simple array of numbers arranged in a single dimension (Rank 1).

    - Example: A list of prices [100, 200, 300].
    - Shape: (n,)

- **Matrix (2D)**: A collection of numbers arranged in a grid with rows and columns (Rank 2).

    - Example: A spreadsheet or a grayscale image.
    - Shape: (rows, columns)

- **Tensor (3D+)**: The generalized term for arrays with 3 or more dimensions (Rank 3+).
    - Example: A color image (Height, Width, Channels) or a video.
    - Shape: (d1, d2, d3, ...)


In [1]:
import numpy as np

In [4]:
#create vector
a= np.array([1,2,3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [6]:
#create matrix
b= np.array([[1,2],[3,4],[5,6]])
print(b)
print(type(b))

[[1 2]
 [3 4]
 [5 6]]
<class 'numpy.ndarray'>


In [11]:
#create tensors
c= np.array([[[1,2,3],[4,5,6]],[[7,8,9],[1,2,3]]])
print(c)
print(type(c))

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [1 2 3]]]
<class 'numpy.ndarray'>


### Custom dtype

In [15]:
d = np.array([1.1,2,3,4,5,0], dtype=bool)
print(d)
print(type(d))

[ True  True  True  True  True False]
<class 'numpy.ndarray'>


In [14]:
e = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype= float)
print(e)
print(type(e))

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
<class 'numpy.ndarray'>


### np.arange() Function
The arange() function returns an ndarray with evenly spaced values within a given interval. 

It is the NumPy equivalent of Python's built-in range() function but returns an array instead of a list.

- **Syntax**: np.arange([start], stop, [step], dtype=None)

- **Key Characteristics**:

    - **Start**: The interval includes this value (default is 0).
    - **Stop**: The interval does not include this value (exclusive).
    - **Step**: The spacing between values (default is 1). This can be a floating-point number, unlike Python's range().

In [16]:
f= np.arange(start=2, stop=10, step=3)
print(f)

[2 5 8]


In [18]:
g= np.arange(1,5,2)
g

array([1, 3])

### np.reshape() Function
The reshape() function changes the shape of an array without changing its data. 

- **Syntax**: array.reshape(shape) 
- **Key Rules**:
    - **Total Elements**: The new shape must be compatible with the original shape. The total number of elements (product of dimensions) must remain the same.
        - *Example*: An array with $12$ elements can be reshaped to $(3, 4)$, $(6, 2)$, or $(2, 2, 3)$, but not $(5, 2)$.
    - **The -1 Shortcut**: You can pass -1 as one of the dimensions. NumPy will automatically calculate the correct value for that dimension based on the remaining elements.
    - **Memory**: Reshaping usually returns a view of the original array, meaning it does not copy the data in memory, making it very efficient.

In [26]:
h = np.arange(1,13).reshape(3,-1)
h

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [28]:
j = np.arange(1,19,3).reshape(2,3)
j

array([[ 1,  4,  7],
       [10, 13, 16]])

### np.zeros() Function
The zeros() function returns a new array of a given shape and type, filled with zeros. It is commonly used as a placeholder before populating an array with actual data.

- **Syntax**: np.zeros(shape, dtype=float)

- **Key Characteristics**:

    - **Shape**: Defines the dimensions of the array (e.g., 5 for a vector, or (3, 4) for a matrix).

    - **Default Dtype**: By default, it creates an array of floats (0.0). You must specify dtype=int if you need integers.

    - **Consistency**: Useful for initializing weights in machine learning or creating masks for image processing.

In [30]:
a= np.zeros(shape=(3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [32]:
b= np.zeros(shape=(3,4), dtype=int)
b

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

### np.ones() Function
The ones() function returns a new array of a given shape and type, filled with ones. This is similar to zeros() but used when the neutral element for multiplication is required.

- **Syntax**: np.ones(shape, dtype=None)

- **Key Characteristics**:

    - **Uniformity**: Every element in the resulting ndarray is exactly 1.
    - **Shape**: Can create any n-dimensional tensor.
    - **Use Case**: Often used to initialize arrays that will be multiplied by other values or to create identity-like structures.

In [34]:
a = np.ones(shape=(3,4), dtype=float)
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [36]:
b= np.ones(shape=(3,4), dtype=int)
b

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [37]:
c= np.ones(shape=(3,4), dtype=bool)
c

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

### np.random Module
The random module in NumPy contains functions for generating arrays of random numbers. Unlike Python’s built-in random library, NumPy's version is optimized for generating large arrays of data simultaneously.

- **Common Functions**:
    - **np.random.rand()**: Generates an array of a given shape with random values from a uniform distribution over $[0, 1)$.
    - **np.random.randn()**: Generates values from a standard normal distribution (mean of $0$ and variance of $1$).
    - **np.random.randint()**: Returns random integers from a specified low (inclusive) to high (exclusive) range.
- **Key Characteristics**:
    - **Reproducibility**: You can use np.random.seed(value) to ensure the "random" numbers generated are the same every time you run the code.
    - **Efficiency**: Designed to produce millions of random samples much faster than standard Python loops.
    - **Statistical Tools**: Provides various distributions like Binomial, Poisson, and Normal for scientific simulations.

In [39]:
a = np.random.rand(3,4)
a

array([[0.97225048, 0.5983443 , 0.34403869, 0.64515279],
       [0.97490412, 0.97142267, 0.78601218, 0.43911129],
       [0.75705197, 0.90561179, 0.03764154, 0.09593077]])

In [ ]:
b= np.random.randn(2,3)
b

array([[ 1.46966555, -0.7739093 , -2.6042506 ],
       [ 0.65578704,  1.11039145, -0.67353939]])

In [ ]:
c= np.random.randint(low=5, high=20, size=(3,4))
c

array([[14, 12, 15, 11],
       [19, 14,  6, 13],
       [17,  5,  8,  5]])

### np.linspace() Function
The linspace() (linear space) function returns an array of evenly spaced numbers over a specified interval. 

While it is similar to arange(), it is specifically designed for cases where you know the number of elements you want rather than the step size.

- **Syntax**: np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)

- **Key Characteristics**:

    - **Start and Stop**: Defines the range of the sequence. Unlike arange(), the stop value is included by default (endpoint=True).

    - **Num**: Specifies the total number of samples to generate. If not provided, it defaults to 50.

    - **Precision**: It calculates the step size automatically to ensure exactly the requested number of elements, making it ideal for creating coordinate grids and plotting functions.

    - **Step Calculation**: If retstep is set to True, the function returns both the array and the calculated step size used between the values.

In [50]:
a = np.linspace(start=10, stop = 100, num = 30, retstep=True)
a

(array([ 10.        ,  13.10344828,  16.20689655,  19.31034483,
         22.4137931 ,  25.51724138,  28.62068966,  31.72413793,
         34.82758621,  37.93103448,  41.03448276,  44.13793103,
         47.24137931,  50.34482759,  53.44827586,  56.55172414,
         59.65517241,  62.75862069,  65.86206897,  68.96551724,
         72.06896552,  75.17241379,  78.27586207,  81.37931034,
         84.48275862,  87.5862069 ,  90.68965517,  93.79310345,
         96.89655172, 100.        ]),
 np.float64(3.103448275862069))

In [52]:
a = np.linspace(start=10, stop = 100, num = 30, retstep=False)
a

array([ 10.        ,  13.10344828,  16.20689655,  19.31034483,
        22.4137931 ,  25.51724138,  28.62068966,  31.72413793,
        34.82758621,  37.93103448,  41.03448276,  44.13793103,
        47.24137931,  50.34482759,  53.44827586,  56.55172414,
        59.65517241,  62.75862069,  65.86206897,  68.96551724,
        72.06896552,  75.17241379,  78.27586207,  81.37931034,
        84.48275862,  87.5862069 ,  90.68965517,  93.79310345,
        96.89655172, 100.        ])

### np.identity() Function
The identity() function creates a square identity matrix of a given size. An identity matrix is a special square matrix with ones on the main diagonal and zeros elsewhere.

- **Syntax**: np.identity(n, dtype=None)
- **Key Characteristics**:
    -  **Square Matrix**: Unlike zeros or ones, identity only takes a single integer n as an argument because the result is always an $n \times n$ square matrix.
    - **Main Diagonal**: The "main diagonal" (from top-left to bottom-right) is populated with 1.0, while all other elements are 0.0.
    - **Mathematical Role**: In linear algebra, multiplying any matrix $A$ by the identity matrix $I$ results in the original matrix $A$ (similar to multiplying a number by $1$).
    - **Default Dtype**: Defaults to float64. You can change this to int or other types using the dtype parameter.

In [53]:
a = np.identity(n = 4, dtype = int)
a

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [54]:
a = np.identity(n = 4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### NumPy Array Attributes
Attributes in NumPy allow you to inspect the intrinsic properties of an ndarray without calling a function. These are essential for debugging and understanding the structure of your data.
- **ndarray.ndim**: Returns the number of dimensions (axes) of the array.   
    - Scalar: 0
    - Vector: 1
    - Matrix: 2
- ndarray.shape: Returns a tuple of integers indicating the size of the array in each dimension.
    - Example: For a matrix with $n$ rows and $m$ columns, the shape will be (n, m).
- ndarray.size: Returns the total number of elements in the array.          
    - Calculation: This is equal to the product of the elements of its shape.
- ndarray.dtype: Returns an object describing the type of the elements in the array.
    - Common Types: int64, float64, bool, complex128.
    - Homogeneity: Since NumPy arrays are homogeneous, every element in the array will share this same dtype.
- ndarray.itemsize: Returns the size in bytes of each element of the array.
    - Example: An array of type float64 (8 bytes) has an itemsize of 8.
    
- ndarray.nbytes: Returns the total bytes consumed by the elements of the array.
    - Calculation: size $\times$ itemsize.

In [57]:
a1 = np.arange(1,11,2)
a2 = np.arange(1,21,2).reshape(2,5)
a3 = np.arange(1,61,3).reshape(2,2,5)

In [64]:
print(a1)
print('')
print(a2)
print('')
print(a3)

[1 3 5 7 9]

[[ 1  3  5  7  9]
 [11 13 15 17 19]]

[[[ 1  4  7 10 13]
  [16 19 22 25 28]]

 [[31 34 37 40 43]
  [46 49 52 55 58]]]


In [59]:
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
3


In [60]:
print(a1.itemsize)
print(a2.itemsize)
print(a3.itemsize)

8
8
8


In [65]:
print(a1.size)
print(a2.size)
print(a3.size)

5
10
20


In [68]:
print(a1.nbytes)
print(a2.nbytes)
print(a3.nbytes)

40
80
160


In [66]:
print(a1.shape)
print(a2.shape)
print(a3.shape)

(5,)
(2, 5)
(2, 2, 5)


Interpretation of (2, 2, 5):

There are 2, (2,5) shape data present in a array.

In [67]:
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
int64
int64


### astype() Function
The astype() function is the primary method used to cast or convert a NumPy array from one data type to another. Since NumPy arrays are homogeneous, this function creates a new copy of the array with the specified dtype.

- **Syntax**: ndarray.astype(dtype, casting='unsafe', copy=True)

- **Key Characteristics**:

    - **Type Conversion**: It allows you to convert between fundamentally different types (e.g., converting Floats to Integers, or Strings to Numbers).

     - **Data Truncation**: When converting from float to int, NumPy will truncate the decimal part (e.g., 3.9 becomes 3), not round it.

    - **Memory Management**: By default, astype() always returns a new copy of the data, even if the destination type is the same as the source type.

    - **Error Handling**: If a conversion is impossible (e.g., converting the string "abc" to an int), it will raise a ValueError.

In [72]:
a = np.array([[[2,3],[4,5]],[[1,2],[3,4]]])
a.dtype

dtype('int64')

In [75]:
a = np.array([[[2,3],[4,5]],[[1,2],[3,4]]]).astype(dtype=np.float32)
print(a)
a.dtype

[[[2. 3.]
  [4. 5.]]

 [[1. 2.]
  [3. 4.]]]


dtype('float32')

In [76]:
a = np.array([[[2,3],[4,5]],[[1,2],[3,4]]]).astype(dtype=np.int16)
print(a)
a.dtype

[[[2 3]
  [4 5]]

 [[1 2]
  [3 4]]]


dtype('int16')

### Array Operations

In [79]:
a1 = np.arange(1,21,2).reshape(2,5)
a2 = np.arange(2,21,2).reshape(2,5)

In [81]:
a1

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

#### Scaler Operations

Arithematic Operations

In [80]:
a1 + 2

array([[ 3,  5,  7,  9, 11],
       [13, 15, 17, 19, 21]])

In [82]:
a1-2

array([[-1,  1,  3,  5,  7],
       [ 9, 11, 13, 15, 17]])

In [83]:
a1*2

array([[ 2,  6, 10, 14, 18],
       [22, 26, 30, 34, 38]])

In [84]:
a1/2

array([[0.5, 1.5, 2.5, 3.5, 4.5],
       [5.5, 6.5, 7.5, 8.5, 9.5]])

In [85]:
a1%2

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [86]:
a2 + 2

array([[ 4,  6,  8, 10, 12],
       [14, 16, 18, 20, 22]])

In [87]:
a2 -4

array([[-2,  0,  2,  4,  6],
       [ 8, 10, 12, 14, 16]])

In [88]:
a2 ** 8

array([[        256,       65536,     1679616,    16777216,   100000000],
       [  429981696,  1475789056,  4294967296, 11019960576, 25600000000]])

Relational Operators

In [89]:
a2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20]])

In [90]:
a2 > 5

array([[False, False,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [93]:
a2 = np.arange(1,21,2).reshape(2,5)

In [95]:
a2

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [94]:
a2 == 4

array([[False, False, False, False, False],
       [False, False, False, False, False]])

In [96]:
a2!= 0

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

## Vector Operation

In [97]:
a1

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [98]:
a2

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [99]:
a1+a2

array([[ 2,  6, 10, 14, 18],
       [22, 26, 30, 34, 38]])

In [100]:
a1 * a2

array([[  1,   9,  25,  49,  81],
       [121, 169, 225, 289, 361]])

In [101]:
a1 / a2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [102]:
a1 % a2

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

## NumPy Statistical & Aggregation Functions

- **np.max()** and **np.min()**: Return the maximum and minimum values in an array, respectively.

    - **Axis Parameter**: You can find the max/min along a specific row (axis=1) or column (axis=0).

- **np.sum()**: Calculates the sum of all elements in the array.

    - **Speed**: It is much faster than the built-in Python sum() for large ndarrays.

- **np.prod()**: Calculates the product of all elements in the array.

- **np.mean()**: Computes the arithmetic average of the elements.

    - **Calculation**: Sum of elements divided by the number of elements.

- **np.median()**: Returns the middle value of the data set.

    - **Robustness**: Unlike the mean, the median is less affected by extreme outliers.

- **np.std()**: Computes the Standard Deviation, which measures the amount of variation or dispersion in the dataset.

    - **Context**: A low standard deviation indicates that the values tend to be close to the mean.

In [103]:
a1

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [106]:
a2 = a2 * 2
a2

array([[ 4, 12, 20, 28, 36],
       [44, 52, 60, 68, 76]])

In [107]:
np.min(a1)

np.int64(1)

In [108]:
np.min(a1, axis=1)

array([ 1, 11])

In [109]:
np.min(a1, axis=0)

array([1, 3, 5, 7, 9])

In [111]:
np.max(a1)

np.int64(19)

In [112]:
np.max(a2, axis = 0)

array([44, 52, 60, 68, 76])

In [113]:
np.max(a2, axis = 1)

array([36, 76])

In [114]:
np.sum(a1)

np.int64(100)

In [115]:
np.sum(a1, axis = 0)

array([12, 16, 20, 24, 28])

In [116]:
np.sum(a1, axis= 1)

array([25, 75])

In [117]:
np.prod(a2)

np.int64(686533194547200)

In [118]:
np.prod(a2, axis = 0)

array([ 176,  624, 1200, 1904, 2736])

In [119]:
np.prod(a2, axis = 1)

array([   967680, 709463040])

In [120]:
np.mean(a1)

np.float64(10.0)

In [121]:
np.mean(a1,axis=1)

array([ 5., 15.])

In [122]:
np.mean(a1, axis = 0)

array([ 6.,  8., 10., 12., 14.])

In [123]:
np.median(a2)

np.float64(40.0)

In [124]:
np.median(a2, axis = 1)

array([20., 60.])

In [125]:
np.median(a2, axis = 0)

array([24., 32., 40., 48., 56.])

### np.var() Function
The var() function calculates the Variance of the elements in an array. Variance is a statistical measurement of the spread between numbers in a data set; it measures how far each number in the set is from the mean.

- **Syntax**: np.var(a, axis=None, dtype=None, ddof=0, keepdims=False)
- **Key Characteristics**:
    - **Calculation**: It is the average of the squared deviations from the mean.
    - **Mathematical Formula**: The variance ($\sigma^2$) is calculated as:$$\sigma^2 = \frac{\sum (x_i - \mu)^2}{N}$$where $x_i$ is each element, $\mu$ is the mean, and $N$ is the number of elements.
    - **Relationship to Standard Deviation**: The variance is simply the square of the standard deviation ($\sigma^2 = \text{std}^2$).
    - **Axis Parameter**: Like other aggregation functions, you can calculate variance for the entire array, column-wise (axis=0), or row-wise (axis=1).

In [126]:
np.std(a1, axis=0)

array([5., 5., 5., 5., 5.])

In [128]:
np.var(a1, axis = 0)

array([25., 25., 25., 25., 25.])

In [130]:
np.std(a2)

np.float64(22.978250586152114)

In [129]:
np.var(a2)

np.float64(528.0)

### Dot Product

In [131]:
a1 = np.arange(1,11).reshape(2,5)
a2 = np.arange(3,13).reshape(5,2)

In [133]:
a1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [134]:
a2

array([[ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [132]:
np.dot(a=a1, b=a2)

array([[125, 140],
       [300, 340]])

In [135]:
np.dot(a1,a2)

array([[125, 140],
       [300, 340]])

### Log and Exponential 

In [136]:
a1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [139]:
a2 = np.log(a1)
a2

array([[0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791],
       [1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509]])

In [140]:
np.exp(a2)

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

## np.round() Function
The round() function rounds an array to the nearest integer or a specified number of decimals.

- **Syntax**: np.round(a, decimals=0)

- **Key Characteristics**:

    - **Precision**: The decimals parameter allows you to round to a specific decimal place (e.g., decimals=2).

    - **Rounding to Even**: NumPy uses "Banker's Rounding." If a number is exactly halfway between two integers (like 0.5 or 1.5), it rounds to the nearest even integer.

    - *Example*: np.round(0.5) is 0.0, and np.round(1.5) is 2.0.

## np.floor() Function

The floor() function returns the largest integer less than or equal to each element (it always rounds down toward negative infinity).

- **Syntax**: np.floor(a)
- **Key Characteristics**:
    - **Direction**: Unlike rounding, it always moves to the left on the number line.
    - **Negative Numbers**: For -1.1, the floor is -2.0 (because $-2$ is smaller than $-1.1$).

## np.ceil() Function

The ceil() (short for "ceiling") function returns the smallest integer greater than or equal to each element (it always rounds up toward positive infinity).
- **Syntax**: np.ceil(a)
- **Key Characteristics**:
     - **Direction**: It always moves to the right on the number line.
     - **Negative Numbers**: For -1.9, the ceil is -1.0 (because $-1$ is larger than $-1.9$).

In [145]:
a1 = np.random.rand(2,3)

In [147]:
a1 = a1 * 100

In [148]:
a1

array([[15.04773345, 73.96934643, 90.8977498 ],
       [75.75566171, 63.72160268, 49.69224405]])

In [149]:
np.ceil(a1)

array([[16., 74., 91.],
       [76., 64., 50.]])

In [150]:
np.floor(a1)

array([[15., 73., 90.],
       [75., 63., 49.]])

In [151]:
np.round(a1)

array([[15., 74., 91.],
       [76., 64., 50.]])

## Indexing and Slicing

Indexing and slicing allow you to access specific elements or sub-sections of an array. In NumPy, this is done using the bracket [] notation.

## Vector Indexing and Slicing (1D)
For a 1D array, indexing works exactly like a standard Python list.

- **Indexing**: Access a single element using its position (starting from 0).

    - *Example*: arr[0] is the first element, arr[-1] is the last.

- **Slicing**: Access a range of elements using the [start:stop:step] syntax.

    - *Note*: The stop index is exclusive.

## Matrix Indexing and Slicing (2D)
In a 2D array, you use two indices separated by a comma: [row, column].

- **Individual Element**: arr[1, 2] accesses the element at row index 1 and column index 2.

- **Slicing Rows/Columns**:

    - *Full Row*: arr[1, :] (Gets all columns in the second row).

    - *Full Column*: arr[:, 2] (Gets all rows in the third column).

    - *Sub-matrix*: arr[0:2, 1:3] (Gets rows 0-1 and columns 1-2).

## Tensor Indexing and Slicing (3D+)
For Tensors, you add more indices separated by commas: [depth, row, column].

- **Accessing a Plane**: arr[0, :, :] (Selects the first 2D matrix/slice in a 3D stack).

- **Accessing a Vector within a Tensor**: arr[0, 1, :] (Selects the second row of the first matrix).

- **The Ellipsis (...)**: If you have many dimensions and want to select all remaining axes, you can use ....

    - *Example*: arr[0, ...] is equivalent to arr[0, :, :].

In [152]:
a1 = np.arange(15).reshape(3,5)
a2 = np.arange(15)
a3 = np.arange(16).reshape(2,2,4)

In [153]:
a1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [154]:
a2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [155]:
a3

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [156]:
a1[0,:]

array([0, 1, 2, 3, 4])

In [157]:
a1[:,0]

array([ 0,  5, 10])

In [158]:
a1[0:2,1:3]

array([[1, 2],
       [6, 7]])

In [159]:
a2[0]

np.int64(0)

In [160]:
a2[-1]

np.int64(14)

In [161]:
a2[0:2]

array([0, 1])

In [165]:
# to extract the 4, 0 here means the first 2-D matric, in this where 4 is located, at 2nd row and 1st col

a3[0,1,0]

np.int64(4)

In [162]:
a3[0,:]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [166]:
a1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [167]:
#Extract each corner
a1[::2,::4]

array([[ 0,  4],
       [10, 14]])

In [170]:
a1[::2, 1:4:2 ] # to get 1,3,11,13

array([[ 1,  3],
       [11, 13]])

In [171]:
a1[1,::4] # to get 5,9

array([5, 9])

In [172]:
a3

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [173]:
#extract 1st 2d arrray's 2nd row
a3[0, 1]

array([4, 5, 6, 7])

In [174]:
#extract first and last columns of previous result
a3[0,1,::3]

array([4, 7])

In [ ]:
#extract 0,3,8,11
a3[:,0,::3]

array([[ 0,  3],
       [ 8, 11]])

## Iteration

In [181]:
a1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [183]:
for i in a1:
    print(i, end=' ')

[0 1 2 3 4] [5 6 7 8 9] [10 11 12 13 14] 

In [186]:
#to get access for each value, use 'nditer'

for i in np.nditer(a1):
    print(i, end=' ')

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 

In [187]:
a3

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [188]:
a3.ndim

3

In [189]:
for i in np.nditer(a3):
    print(i, end = ' ')

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 

## Transpose (.T Attribute)

The Transpose of a matrix is an operator that flips a matrix over its main diagonal, switching its row and column indices.
- **Syntax**: array.T or np.transpose(array)
- **Key Characteristics**:
    - **Dimension Swap**: For a 2D array of shape $(n, m)$, the transpose will have a shape of $(m, n)$.
    - **1D Arrays**: Transposing a 1D array (vector) has no effect because it only has one axis. To turn a 1D vector into a column vector, you must first reshape it to 2D.
    - **View vs. Copy**: Like reshape, .T usually returns a view of the original array, making it an $O(1)$ operation in terms of time and memory.
    - **Higher Dimensions**: For tensors, .T reverses the order of the axes (e.g., a shape of $(2, 3, 4)$ becomes $(4, 3, 2)$).

In [190]:
a3

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [191]:
a3.shape

(2, 2, 4)

In [192]:
a3.T

array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

In [193]:
a3.T.shape

(4, 2, 2)

In [194]:
np.transpose(a3)

array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

In [195]:
np.transpose(a3).shape

(4, 2, 2)

## np.ravel() Function
The ravel() function is used to flatten a multi-dimensional array into a 1-dimensional array.

- **Syntax**: np.ravel(array, order='C')

- **Key Characteristics**:

    - *Flattening*: It unrolls the array into a single line of data.

    - *Memory Efficiency*: Unlike ndarray.flatten(), which always returns a copy, ravel() returns a view whenever possible. Modifying the raveled array may modify the original array.

    - *Order Parameter*:

        - **'C'**: (Default) Flattens row-by-row (C-style).

        - **'F'**: Flattens column-by-column (Fortran-style).

In [196]:
a1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [197]:
np.ravel(a1, order='C')

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [198]:
np.ravel(a1, order= 'F')

array([ 0,  5, 10,  1,  6, 11,  2,  7, 12,  3,  8, 13,  4,  9, 14])

# Stacking in NumPy

Stacking is the process of joining a sequence of arrays along a new or existing axis. It is essential for combining datasets, such as merging multiple image channels or adding new observations to a data matrix.


## np.vstack() (Vertical Stack)

The vstack() function stacks arrays in sequence vertically.

- **Syntax**: np.vstack((array1, array2, ...))
- **Key Characteristics**:
    - *Requirement*: The arrays must have the same number of columns.
    - *Dimensionality*: Increases the number of rows.
    - *Use Case*: Adding new rows (samples) to an existing dataset.

In [200]:
a1= np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

In [201]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [202]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [203]:
np.vstack(tup=(a1,a2))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [204]:
np.vstack(tup=(a2,a1))

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

## np.hstack() (Horizontal Stack)
The hstack() function stacks arrays in sequence horizontally (column-wise).

- **Syntax**: np.hstack((array1, array2, ...))

- **Key Characteristics**:

    - *Requirement*: The arrays must have the same number of rows.

    - *Dimensionality*: Increases the number of columns.

    - *Use Case*: Adding new features (columns) to an existing dataset.

In [205]:
np.hstack(tup=(a1,a2))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [210]:
a3 = np.hstack(tup=(a2,a1))
a3

array([[12, 13, 14, 15,  0,  1,  2,  3],
       [16, 17, 18, 19,  4,  5,  6,  7],
       [20, 21, 22, 23,  8,  9, 10, 11]])

# Splitting in NumPy
Splitting is the analytical opposite of stacking. It allows you to break a single array into multiple smaller sub-arrays along a specified axis.

## np.vsplit() (Vertical Split)
The vsplit() function splits an array into multiple sub-arrays row-wise. It only works on arrays with at least 2 dimensions.

- **Syntax**: np.vsplit(array, indices_or_sections)

- **Key Characteristics**:

    - *Sections*: If an integer is passed, the array is split into that many equal parts.

    - *Indices*: If a list of integers is passed, it splits at those specific row indices.

    - *Requirement*: The number of rows must be divisible by the number of sections.

In [215]:
a3

array([[12, 13, 14, 15,  0,  1,  2,  3],
       [16, 17, 18, 19,  4,  5,  6,  7],
       [20, 21, 22, 23,  8,  9, 10, 11]])

In [214]:
np.vsplit(a3,3)

[array([[12, 13, 14, 15,  0,  1,  2,  3]]),
 array([[16, 17, 18, 19,  4,  5,  6,  7]]),
 array([[20, 21, 22, 23,  8,  9, 10, 11]])]

In [216]:
np.vsplit(a3,[0,1])

[array([], shape=(0, 8), dtype=int64),
 array([[12, 13, 14, 15,  0,  1,  2,  3]]),
 array([[16, 17, 18, 19,  4,  5,  6,  7],
        [20, 21, 22, 23,  8,  9, 10, 11]])]

## np.hsplit() (Horizontal Split)
The hsplit() function splits an array into multiple sub-arrays column-wise.

- **Syntax**: np.hsplit(array, indices_or_sections)

- **Key Characteristics**:

    - *Direction*: It cuts the array "down the middle" of the columns.

    - *Use Case*: Separating a target label column from a feature matrix in machine learning.

    - *Requirement*: The number of columns must be divisible by the number of sections.

In [217]:
a3

array([[12, 13, 14, 15,  0,  1,  2,  3],
       [16, 17, 18, 19,  4,  5,  6,  7],
       [20, 21, 22, 23,  8,  9, 10, 11]])

In [219]:
np.hsplit(a3, 2)

[array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]),
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])]

In [220]:
np.hsplit(a3,[2,4,5])

[array([[12, 13],
        [16, 17],
        [20, 21]]),
 array([[14, 15],
        [18, 19],
        [22, 23]]),
 array([[0],
        [4],
        [8]]),
 array([[ 1,  2,  3],
        [ 5,  6,  7],
        [ 9, 10, 11]])]